version: "2"

services:
  bnb-starter-kit:
    container_name: bnb-starter-kit
    image:          ${DOCKER_ID_USER}/bnb-starter-kit:latest
    ports:
      - 4000:4000
      - 6000:6000
    env_file:
      - .env
